# Generated by Django 5.1.4 on 2024-12-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='district',
            field=models.CharField(choices=[('Castries', 'Castries'), ('Gros Islet', 'Gros Islet'), ('Vieux Fort', 'Vieux Fort'), ('Soufriere', 'Soufriere'), ('Micoud', 'Micoud'), ('Dennery', 'Dennery'), ('Laborie', 'Laborie'), ('Choiseul', 'Choiseul'), ('Anse La Raye', 'Anse La Raye'), ('Canaries', 'Canaries'), ('All', 'All Districts')], default='All', max_length=20),
        ),
    ]
