# Generated by Django 5.0.2 on 2025-03-09 13:41

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_incident_affected_area_alter_incident_location_and_more'),
        ('resource_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='distribution_area',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='priority',
            field=models.IntegerField(default=0, help_text='Priority level of the request'),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='resourcerequest',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resource_management.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='resourcerequest',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Request location', srid=4326),
        ),
        migrations.AlterField(
            model_name='resourcerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('SHELTER', 'Shelter'), ('MEDICAL', 'Medical'), ('SUPPLIES', 'Supplies'), ('WATER', 'Water')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('LIMITED', 'Limited'), ('UNAVAILABLE', 'Unavailable'), ('ASSIGNED', 'Assigned')], default='AVAILABLE', max_length=20)),
                ('capacity', models.IntegerField(help_text='Maximum capacity/quantity of this resource')),
                ('current_count', models.IntegerField(help_text='Current available quantity')),
                ('current_workload', models.IntegerField(default=0, help_text='Current usage/assignment load')),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Geographic coordinates', srid=4326)),
                ('address', models.CharField(max_length=255)),
                ('coverage_area', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Area this resource can service', null=True, srid=4326)),
                ('last_assignment_cost', models.FloatField(blank=True, help_text='Cost metric from last assignment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_resources', to='incidents.incident')),
                ('managed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_resources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='distribution',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='resource_management.resource'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='resource_management.resource'),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='resource_management.resource'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['resource_type', 'status'], name='resource_ma_resourc_d2b408_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['created_at'], name='resource_ma_created_51f6d5_idx'),
        ),
    ]
