# Generated by Django 5.0.2 on 2025-03-09 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0002_distribution_distribution_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='assigned_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_resource', to='resource_management.resourcerequest'),
        ),
    ]
