# Generated by Django 5.1.7 on 2025-03-17 03:23

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0003_resource_assigned_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('supplier_type', models.CharField(choices=[('MEDICAL', 'Medical Supplies'), ('FOOD', 'Food and Water'), ('SHELTER', 'Shelter Materials'), ('EQUIPMENT', 'Equipment'), ('OTHER', 'Other Supplies')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Geographic coordinates', null=True, srid=4326)),
                ('website', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending Approval')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['supplier_type', 'status'], name='resource_ma_supplie_d4c116_idx'), models.Index(fields=['created_at'], name='resource_ma_created_5bad7f_idx')],
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_items', to='resource_management.supplier'),
        ),
    ]
