# Generated by Django 5.1.7 on 2025-03-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0004_supplier_inventoryitem_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='item_type',
            field=models.CharField(choices=[('NONE', 'None'), ('MEDICAL', 'Medical'), ('WATER', 'Water'), ('FOOD', 'Food'), ('SHELTER', 'Shelter/Warmth'), ('TOOLS', 'Tools/Equipment'), ('POWER', 'Power/Light'), ('COMMUNICATION', 'Communication'), ('SANITATION', 'Sanitation/Hygiene'), ('CLOTHING', 'Clothing'), ('TRANSPORTATION', 'Transportation'), ('SPECIAL_NEEDS', 'Special Needs')], default='NONE', max_length=20),
        ),
    ]
