# Generated by Django 5.1.4 on 2024-12-14 22:06

import incidents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='incident',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=incidents.models.incident_photo_path),
        ),
    ]
