# Generated by Django 5.1.4 on 2025-03-03 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_alter_incident_options_remove_incident_photo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='status',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='verified_by',
        ),
        migrations.AddField(
            model_name='incident',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='incidents/'),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='incident',
            name='location',
            field=models.CharField(default='Location not specified', max_length=255),
        ),
        migrations.AlterField(
            model_name='incident',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('EXTREME', 'Extreme')], max_length=10),
        ),
        migrations.AlterField(
            model_name='incident',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
