# Generated by Django 5.1.6 on 2025-03-09 00:30

import django.contrib.gis.db.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_remove_incident_assigned_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='affected_area',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Geographic area affected by the incident', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='incident',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Geographic coordinates of the incident', srid=4326),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['-created_at'], name='incidents_i_created_c4c91a_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['location'], name='incidents_i_locatio_93f319_idx'),
        ),
    ]
