# Generated by Django 5.1.7 on 2025-03-31 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_incident_affected_area_alter_incident_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='location_name',
            field=models.CharField(blank=True, help_text='Approximate community/district name (auto-generated)', max_length=255, null=True),
        ),
    ]
