# Generated by Django 5.1.4 on 2025-03-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customgroup_alter_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='group_type',
            field=models.CharField(choices=[('ADMINISTRATOR_GROUP', 'Administrator Group'), ('CITIZEN_GROUP', 'Citizen Group'), ('EMERGENCY_GROUP', 'Emergency Personnel Group'), ('RESOURCE_MANAGER_GROUP', 'Resource Manager Group'), ('MEDICAL_PERSONNEL_GROUP', 'Medical Personnel Group')], default='CITIZEN_GROUP', help_text='Type of the group determining its role in the system', max_length=50, unique=True),
        ),
    ]
