# Generated by Django 5.1.4 on 2025-03-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_permissioncategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissioncategory',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of what this category of permissions encompasses'),
        ),
        migrations.AlterField(
            model_name='permissioncategory',
            name='name',
            field=models.CharField(help_text="Name of the permission category (e.g., 'Citizen permissions')", max_length=100, unique=True),
        ),
    ]
