# Generated by Django 5.1.7 on 2025-03-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_additional_info_user_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text="Indicates if the user's credentials have been verified"),
        ),
    ]
