# Generated by Django 5.1.4 on 2025-03-03 02:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('HURRICANE_WATCH', 'Hurricane Watch'), ('HURRICANE_WARNING', 'Hurricane Warning'), ('FLOOD_WATCH', 'Flood Watch'), ('FLOOD_WARNING', 'Flood Warning'), ('SEVERE_WEATHER', 'Severe Weather'), ('TORNADO_WATCH', 'Tornado Watch'), ('TORNADO_WARNING', 'Tornado Warning')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('EXTREME', 'Extreme')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('area_affected', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('feels_like', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.IntegerField()),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wind_direction', models.IntegerField()),
                ('conditions', models.CharField(choices=[('SUNNY', 'Sunny'), ('PARTLY_CLOUDY', 'Partly Cloudy'), ('CLOUDY', 'Cloudy'), ('RAIN', 'Rain'), ('STORM', 'Storm'), ('HURRICANE', 'Hurricane')], max_length=20)),
                ('pressure', models.DecimalField(decimal_places=2, max_digits=6)),
                ('visibility', models.DecimalField(decimal_places=2, max_digits=5)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('high_temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('low_temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('conditions', models.CharField(choices=[('SUNNY', 'Sunny'), ('PARTLY_CLOUDY', 'Partly Cloudy'), ('CLOUDY', 'Cloudy'), ('RAIN', 'Rain'), ('STORM', 'Storm'), ('HURRICANE', 'Hurricane')], max_length=20)),
                ('precipitation_chance', models.IntegerField()),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('date', 'location')},
            },
        ),
    ]
